### ISSUE TITLE
Dynamic or static timestamp

### ISSUE THREAD

**Issue by 4straction** [paytrail/examples#10]
In file CalculateMerchantApiHash.php line 38 you have:

$timestamp = (new DateTime())->format(DateTimeInterface::RFC3339); // 2020-05-01T12:00:00+0300

Should timestamp be also hard coded in the code for this examplotary purpose? .. since every run will now give a different signature. To validate the logic, using hard coded timestamp from the comment (2020-05-01...) always generated the following signature:

6aqkEbYJ6PVwQgY7fH2g2uopKDsoQIL4JT+7/ldmtGQ=

Using perl, c# and that example php logic as it was. Missing something here, or a mismatch with the timestamp used here compared to the signatures in the comments?

**Comment by Jipsukka** [comment]
Since it's example how to get timestamp in real world scenario, it should not have hard coded timestamp.
However, there was a copy paste error in URL, which leads also wrong signature in comment.
Correct URL would be `/merchant/v1/payments/102402728626/refunds` which should give signature `tc51Vrg3HuLvwE1v0vul95Ux2hIE+COC3kT4EohrqTI=` when string `2020-05-01T12:00:00+0300` is used for `$timestamp`.
There's pull request to fix this issue.

In real world implementation you should always generate new timestamp for each API call, which would give you unique signature for each call. Just remember to use exact same generated timestamp for both signature and request headers.

**Comment by Jipsukka** [comment]
Closing this issue, since it's no longer relevant. PR #11 fixed wrong signature, which probably caused this issue as well. If there's need to clarify timestamp usage, that should be in documentation. Examples should only show one case to support documentation, not explain whole process.
